### ISSUE TITLE
toolrunner

### ISSUE THREAD

**Issue by dalexander** [PacificBiosciences/pbcommand#1]
Would you be interested in migrating "ToolRunner" functionality from pbcore to pbcommand?

Something to think about.

**Comment by dalexander** [comment]
another possibility would be merging pbcommand and pbcore, but i know some people prefer more modularity.

**Comment by mpkocher** [comment]
I think deprecating ToolRunner and PBMultiToolRunner would be best. pbcommand should be the new model. Even if you don't use the tool contract abstractions, there's a simple wrapper for argparse that provides a consistent layer. I can put an example up.

Similarly, I think moving pbcore.util.Process to pbcommand might be useful. Thoughts?

**Comment by mpkocher** [comment]
Here's a pure argparse example (i.e., nothing to do with the tool contract)

[Example](https://github.com/mpkocher/pbcommand-examples/blob/master/hello_world.py)

The "runner" func names from pbcommand.cli are not particularly great. Open to suggestions. I was attempting to be more verbose.

**Comment by dalexander** [comment]
OK we can talk about that next week

**Comment by mpkocher** [comment]
There's a wrapper around Popen in pbcommand.engine.runner.
