### ISSUE TITLE
Add --non-local to import-dataset

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/pbcommand#112]
Currently, Importing datasets can only be done with access to the FS where the dataset exists.

Expand importing to include non-local (to where pbservice is running) importing of datasets would require:
- explicitly providing the DataSet metatype
- skipping any validation
- calling 'ServiceAccessLayer.run_import_dataset_by_type' instead of 'run_import_local_dataset'

**Comment by mpkocher** [comment]
@natechols can you move these to smrtflow?

**Comment by natechols** [comment]
https://github.com/PacificBiosciences/smrtflow/issues/178
