### ISSUE TITLE
How do I set filenames with @registry()?

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pbcommand#20]
I have code like this:

``` python
def FT(file_type, basename):
    return OutputFileType(file_type.file_type_id,
                          "Label " + file_type.file_type_id,
                          repr(file_type),
                          "description for {f}".format(f=file_type),
                          basename)

@registry('task_falcon_build_rdb', '0.0.0', [FC_JSON, FC_FOFN], [FT(FC_BASH, 'script.sh'), FT(FC_DUMMY, 'DUMMY1.txt')], is_distributed=False)
def run_rtc(rtc):
    ...
```

When I run regenerate-tool-contracts.py, I get this:

``` json
        "output_types": [
            {
                "default_name": "script.sh",
                "description": "description for <FileType id=PacBio.FileTypes.txt name=file.txt >",
                "file_type_id": "PacBio.FileTypes.txt",
                "id": "Label PacBio.FileTypes.txt",
                "title": "<FileType id=PacBio.FileTypes.txt name=file.txt >"
            },
            ...
```

And at runtime, the file is called `file.txt`, not `script.sh`. Worse, both outputs are assigned the same filename.
1. Isn't this a bug? (2 outputs, 1 filename)
2. How can I set the filename(s) myself?

**Comment by natechols** [comment]
Actually, I'm wrong, I think the bug I'm fighting is actually in pbsmrtpipe - same outcome, but might be a different code path.  (It is simply ignoring the desired file names in the resolved tool contract and replacing them with the per-file-type defaults.)

**Comment by pb-cdunn** [comment]
PacificBiosciences/pbsmrtpipe#38 fixed the problem. Thx. (I had a work-around already too.)
