### ISSUE TITLE
OutputFileType updated to have basename_default

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/pbcommand#22]
The API for TC parser model needs to be updated to specify the base file name of the output file.

Currently, the models support default file name as ("base_name, "ext") or "base_name.ext" The file extension does not need to be specified, it will be set by the FileType instance that is provided. Hence only the basename of the file needs to be provided.

Unfortunately, this will require changing all of the pbpbarser calls  to add_output_file_type and to regenerate all the TCs. It would probably be useful to make the default output file name optional in the add_output_file_type function.

**Comment by mpkocher** [comment]
@natechols Is this fixed by a (somewhat) recent change to the TC/RTC model?

**Comment by natechols** [comment]
Yes.
