### ISSUE TITLE
report IO uses inconsistent versions

### ISSUE THREAD

**Issue by natechols** [PacificBiosciences/pbcommand#30]
The output JSON dict specifies the pbcommand version (0.2.15), but load_report_from_json seems to be expecting a schema version (?) chosen from, so I get this::

  WARNING:pbcommand.pb_io.report:0.2.15 is an unsupported version. Supported versions ('2.1', '2.2', '2.3')

Clearly one of these is wrong; my preference would be to use the pbcommand version only.

**Comment by mpkocher** [comment]
For context, the old model in SA2.3 was to use the release version of SA. 

My proposal is that the version in pbreport model should correspond to the schema version of report model. I don't believe there were schema changes in 2.1, 2.2, or 2.3, so changing the version is bit confusing. Storing the author component version of the JSON report would be useful, but it wasn't in the original model.

I've commented out the warning.

**Comment by mpkocher** [comment]
@natechols Are you okay with migrating to using the schema version?

**Comment by natechols** [comment]
Sure, I doubt this will break anything (and if not, I'm pretty confident that we'll catch it quickly in integration testing)

**Comment by mpkocher** [comment]
I'm setting this as resolved with 4d3875124e09523a38477bcc857c08424f1650f7
