### ISSUE TITLE
PEP8?

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pbcommand#4]
I like [this](285dad3106197eb42e722f689e627bde9557a393) a lot:

```
commit 285dad3106197eb42e722f689e627bde9557a393
Author: mpkocher <michael.kocher@me.com>
Date:   Wed Jul 22 00:03:22 2015

    closer to pep8
```

But it's not consistent with the [pacbioStyleGuide](http://smrtanalysis-docs/style_guide.html), whichMandatesCamelCase:

Maybe we should lobby ~~Scott~~ Aaron to go with PEP8?

**Comment by pb-jchin** [comment]
+1 on "Maybe we should lobby Scott to go with PEP8?"

**Comment by dalexander** [comment]
that's a question for Aaron, not Scott

**Comment by mpkocher** [comment]
We can discuss this internally. 

I'm using these make targets in a few projects now.

```
run-pep8:
    find pbcommand -name "*.py" -exec pep8 --ignore=E501,E265,E731,E402 {} \;

run-auto-pep8:
    find pbcommand -name "*.py" -exec autopep8 -i --ignore=E501,E265,E731,E402 {} \;
```
