### ISSUE TITLE
Add log_level support to RTC

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/pbcommand#40]
Currently, there's not a way to call driver (e.g., run-rtc /path/to/rtc.json) with the logging level. 

For the quick registry RTC model, this can be fixed pretty easily. However, for the general RTC runner model, this might require a bit thought on how the current setup_log_func model can access rtc.log_level.

**Comment by pb-cdunn** [comment]
Related: #76
See also: https://bugzilla.nanofluidics.com/show_bug.cgi?id=30788

**Comment by natechols** [comment]
I'm pretty sure I fixed this.
