### ISSUE TITLE
--quiet option only partially successful

### ISSUE THREAD

**Issue by natechols** [PacificBiosciences/pbcommand#50]
It does not prevent a handful of INFO messages from being printed:

```
$ ipdSummary --quiet --numWorkers 1 --csv tmp.csv --gff tmp.gff --summary_h5 tmp.h5 --control $INPUT --reference $REFERENCE $INPUT
[INFO] 2016-01-13 18:00:13,856Z [root _pacbio_main_runner 96] Using pbcommand v0.3.9
[INFO] 2016-01-13 18:00:13,857Z [root _pacbio_main_runner 97] completed setting up logger with <function setup_log at 0x7f1a9fbf21b8>
[INFO] 2016-01-13 18:00:13,857Z [root _pacbio_main_runner 98] log opts {'file_name': None, 'level': 20}
```

--log-level=WARNING does get rid of these messages; I had expected --quiet to be similar if not even more restrictive.

**Comment by mpkocher** [comment]
Is ipdSummary a "wrapper" to pbcore PbToolRunner interface?

**Comment by natechols** [comment]
No, although it does have some log setup code that should probably be cleaned up (but which I thought would prevent output like this).

**Comment by mpkocher** [comment]
This looks like it's fixed if you're using the pbcommand setup logging. If you still are seeing problems, I would suggest looking into the layer that's calling the pbcore tool wrapper layer.

mkocher@login14-biofx01:tmp$ pbservice get-dataset 1234 --host=smrtlink-beta --port=8081 --quiet
{ u'comments': u' ',
  u'createdAt': u'2015-12-15T22:55:40.041',
  u'id': 1234,
  u'isActive': True,
  u'jobId': 751,
  u'md5': u'39a5f5760e7253517483680c2db0e86e',
  u'name': u'SubreadSetFromMetadata',
  u'numRecords': 1031709,
  u'path': u'/pbi/collections/312/3120046/r54009_20151215_215544/3_A01/m54009_151215_223334.subreadset.xml',
  u'projectId': 1,
  u'tags': u'subreadset',
  u'totalLength': 601038865,
  u'updatedAt': u'2015-12-15T22:55:40.041',
  u'userId': 1,
  u'uuid': u'a68b67e9-5b30-4c66-8078-df3ff75050ca',
  u'version': u'3.0.0'}
mkocher@login14-biofx01:tmp$ pbservice get-dataset 1234 --host=smrtlink-beta --port=8081
[INFO] 2016-04-16 19:09:47,051 Starting tool version 0.2.0
[INFO] 2016-04-16 19:09:47,067 Starting new HTTP connection (1): smrtlink-beta
[INFO] 2016-04-16 19:09:47,074 Starting new HTTP connection (1): smrtlink-beta
{ u'comments': u' ',
  u'createdAt': u'2015-12-15T22:55:40.041',
  u'id': 1234,
  u'isActive': True,
  u'jobId': 751,
  u'md5': u'39a5f5760e7253517483680c2db0e86e',
  u'name': u'SubreadSetFromMetadata',
  u'numRecords': 1031709,
  u'path': u'/pbi/collections/312/3120046/r54009_20151215_215544/3_A01/m54009_151215_223334.subreadset.xml',
  u'projectId': 1,
  u'tags': u'subreadset',
  u'totalLength': 601038865,
  u'updatedAt': u'2015-12-15T22:55:40.041',
  u'userId': 1,
  u'uuid': u'a68b67e9-5b30-4c66-8078-df3ff75050ca',
  u'version': u'3.0.0'}
[INFO] 2016-04-16 19:09:47,085 exiting with return code 0 in 0.03 sec.

**Comment by natechols** [comment]
Yes, this was something I specifically checked for when I made the logging changes.
