### ISSUE TITLE
is_distributed in RTC

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pbcommand#54]
Oddly, `is_distributed` is `true` even when we use `--force-local`. The job is correctly run on the local machine, not via qsub, so there is no bug. But it's odd.

`nproc` is properly constrained by `max_nproc`, so you cannot say that the arguments to `@registry` (_i.e._ `RegistryBuilder`) are simply repeated.

I'm just pointing this out.

**Comment by mpkocher** [comment]
Enumerating the necessary changes.
- pbcommand: add  new positional arg of is_distributable to resolve_tool_contract
- pbcommand: update testkit to have IS_DISTRIBUTABLE that will be passed to the resolver (should be false be default)
- pbcommand: update tests
- pbsmrtpipe: add local var in driver is_workflow_distributable = global_registry.cluster_renderer is not None
- pbsmrtpipe: update static_meta_task_to_rtc and friends with new positional arg (remove the legacy rtc.task.is_distributed calls)

**Comment by natechols** [comment]
Sorry, I'm confused - what is pbcommand supposed to do with is_distributable internally?

**Comment by mpkocher** [comment]
The RTC value should be true only if both the resolver is true and the TC value is true. Currently, the resolving process to determine is_distributed is only a function of the TC value.

When users run pbsmrtpipe with local only, then the value passed into the resolver is false (i.e.,  global_registry.cluster_renderer is None), then all RTCs should have is_distributed as false.

**Comment by natechols** [comment]
@pb-cdunn can you please verify that the new behavior is what you expect?

**Comment by pb-cdunn** [comment]
@natechols, I'm sure it's fine. I was only pointing out an oddity, not a problem in behavior. It's good that this has been clarified.
