### ISSUE TITLE
Consider adding --to-json to pbservice

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/pbcommand#71]
Adding an `--to-json` option to `pbservice` might enable useful processing of the output via `jq`

https://stedolan.github.io/jq/

**Comment by mpkocher** [comment]
@natechols can you move this to smrtflow? The pbservice CLI exe won't be adding any features.

**Comment by natechols** [comment]
This is actually done in smrtflow, except I think I made it `--as-json`
instead of `--to-json` (but we can change that).
