### ISSUE TITLE
Consider Model for -v short cut for increasing log verbosity

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/pbcommand#76]
Dave and Lance have suggested using -v and -vv to increase the log level.

`-v` and `--version` are currently added by default in argparse.

Current base options:

```
optional arguments:
  -h, --help            show this help message and exit
  --log-file LOG_FILE   Write the log to file. Default(None) will write to
                        stdout. (default: None)
  --log-level {DEBUG,INFO,WARNING,ERROR,CRITICAL}
                        Set log level (default: INFO)
  --debug               Alias for setting log level to DEBUG (default: False)
  --quiet               Alias for setting log level to CRITICAL to suppress
                        output. (default: False)
```

**Comment by nlhepler** [comment]
Hilariously, argparse seems to have removed the version support in py3.

**Comment by pb-cdunn** [comment]
@pb-cdunn has suggested using a logging config file. For convenience, provide a tool which dumps the logging-config (as .json or even .ini). That would give us all sorts of flexibility, transparency, and simple coding. As opposed to misunderstandings, a complicated API, and a stream of bugs.

**Comment by dalexander** [comment]
@mpkocher had some discussion with us on this issue.  I am happy we have resolved the `-v` issue, in 6c89b306ad3c902ab5df008d41abbba1a2c25c83.  

I am willing to yield on my position of what "--debug" means... if you would like to use --debug, I could switch my code over to --pdb.

**Comment by mpkocher** [comment]
I don't have strong options about these cli options. My main motivation is iterating towards some semblance of a consistent interface.

My proposal is:
- fold the `-v`  `--verbose` model back into pbcommand
- keep `--debug` as a shortcut for `--log-level=DEBUG` in pbcommand, the base options should included this
- keep `--quiet` as a shortcut for `--log-level=ERROR` (quiver already has this)
- move quiver to use of `--debug` to `--pdb` 
- add `--pdb` to pbcommand (use pdb or drop into ipdb if installed)

The `--verbose`, `--quiet`, `--debug` should be mutually exclusive options add to the base options.

This adds a bit of degeneracy to configure the log level but this keeps the current command line interfaces of both "styles" with minimal breakage. The `--pdb` use case is for interactive use, and users should be able to sort this out via `--help`.

Does this seem reasonable?

**Comment by nlhepler** [comment]
This seems entirely reasonable to me. As for logging config files, @pb-cdunn, I like the idea, but configuration files are orthogonal or complementary to a properly useful cmdline API, not a replacement.

**Comment by natechols** [comment]
Okay, with my local changes (pull request imminent), I get these options as part of the default argparser:

```
optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  --log-file LOG_FILE   Write the log to file. Default(None) will write to
                         stdout. (default: None)
  --log-level {DEBUG,INFO,WARNING,ERROR,CRITICAL}
                    Set log level (default: INFO)
  --debug               Alias for setting log level to DEBUG (default: False)
  --quiet               Alias for setting log level to CRITICAL to suppress
                        output. (default: False)
  -v, --verbose         Set the verbosity level. (default: None)
```

This is going to break GenomicConsensus but it's an easy fix.

**Comment by natechols** [comment]
https://github.com/PacificBiosciences/pbcommand/pull/88

**Comment by mpkocher** [comment]
Thanks @natechols for enhancements.
