### ISSUE TITLE
logging/debugging

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pbcommand#84]
```
resolved-tool-contract.json:
{
    "driver": {
        "exe": "python -m pbcoretools.tasks.converters  run-rtc  ",
...
}

pbcoretools/tasks/converters.py:
235 if __name__ == '__main__':
236     sys.exit(registry_runner(registry, sys.argv[1:]))

pbcommand/cli/quick.py:
283 def registry_runner(registry, argv):
299     log.info("Running registry {r} with args {a}".format(r=registry, a=argv))
300     f = _to_registry_parser('0.1.1', "Multi-quick-tool-runner for {r}".format(r=registry.namespace))
301     p = f(registry)
302     args = p.parse_args(argv)
```

A) The registry_runner() actually logs before a logger has been configured.
B) The default arguments to registry_runner() do not provide a way to turn on the logger (let alone to configure logging).
C) I need to step through pbcoretools in order to debug a problem with dataset conversion.
I have some other options for debugging (hack the code, _read_ the code, wrap the whole thing), but there seem to be some low-hanging fruit here:
1. `registry_runner` options for logging would be easy to add.
2. `--pdb` is another dirt-simple option. It could be in registry_runner as well as [some of the other front-ends](https://github.com/PacificBiosciences/pbcommand/blob/master/pbcommand/common_options.py#L10). (I think I've seen it used somewhere, but I don't remember where at the moment.) Just [set up `sys.excepthook`](http://code.activestate.com/recipes/65287/). But the most useful spot for me is in the commonly-used `registry_runner()`.
3. `python -m pdb pbwrapper.py -- pbcoretools.tasks.converters  run-rtc resolved-tool-contract.json` would be pretty helpful. For that, we need a wrapper which will import and run the argument. (Maybe this already exists in some form? I cannot remember clearly all the APIs available in `pb*`.) Of course, this is something I can do myself too, if nothing similar exists.

**Comment by mpkocher** [comment]
There's not a whole lot going on at the TC/RTC level in this specific case. I'll investigate the issues you mentioned.  

In the meantime, I would suggest loading the main function of interest from pbcoretools in ipython to debug the problem. 

For example, run_bam_to_fastq in https://github.com/PacificBiosciences/pbcoretools/blob/master/pbcoretools/tasks/converters.py#L222

**Comment by pb-cdunn** [comment]
Thank you for your kind advice and your analysis. I won't need anything further from you. I will close this now.
